### ISSUE TITLE
incorrect mime type

### ISSUE THREAD

**Issue by zwhitchcox** [fewstera/go-wasm-ball-drop-game#2]
`Uncaught (in promise) TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.`

in my browser when running the example

**Comment by fewstera** [comment]
@zwhitchcox are you serving the content using the provided server (server.go) and are you running Golang 1.11?

**Comment by zwhitchcox** [comment]
Oh, sorry, I had the compiler and the server running two different go versions. I didn't know it mattered if the server ran go 1.10

**Comment by zwhitchcox** [comment]
Also, do you mind me asking why the file size is so big? I was thinking of using go and wasm for my new app, but I really don't want to have to serve 3.2MB files

**Comment by fewstera** [comment]
I'm not 100% sure, this is the first time I've played around with wasm.

It might be due to the packages I've included, as removing golang.org/x/text/language and golang.org/x/text/message (used only for comma separating numbers) it reduces down to 2.4MB.

**Comment by zwhitchcox** [comment]
Hmmm, interesting, ok, thanks!

Weird it would increase the size by that much though
